// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkhHQS6OnWyCyewUsIY3SW3WTr8nxfb6s',
    appId: '1:351823626349:web:10e482a35c86754949ff64',
    messagingSenderId: '351823626349',
    projectId: 'bluemind-61ea7',
    authDomain: 'bluemind-61ea7.firebaseapp.com',
    storageBucket: 'bluemind-61ea7.firebasestorage.app',
    measurementId: 'G-40S0H03C08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7-PoKqfAtNi5baTBykDZeXuga_QfyT9Q',
    appId: '1:351823626349:android:285d252b84dbf00449ff64',
    messagingSenderId: '351823626349',
    projectId: 'bluemind-61ea7',
    storageBucket: 'bluemind-61ea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAHnqkCzSufv8WTOcyqO0W9zB9q8xnNhI',
    appId: '1:351823626349:ios:af79fbced2ded73349ff64',
    messagingSenderId: '351823626349',
    projectId: 'bluemind-61ea7',
    storageBucket: 'bluemind-61ea7.firebasestorage.app',
    iosClientId: '351823626349-i3mtbgkut4rkj107drmddn5saf5dv7hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.blueMindWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAHnqkCzSufv8WTOcyqO0W9zB9q8xnNhI',
    appId: '1:351823626349:ios:af79fbced2ded73349ff64',
    messagingSenderId: '351823626349',
    projectId: 'bluemind-61ea7',
    storageBucket: 'bluemind-61ea7.firebasestorage.app',
    iosClientId: '351823626349-i3mtbgkut4rkj107drmddn5saf5dv7hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.blueMindWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkhHQS6OnWyCyewUsIY3SW3WTr8nxfb6s',
    appId: '1:351823626349:web:b9ade0beca56977549ff64',
    messagingSenderId: '351823626349',
    projectId: 'bluemind-61ea7',
    authDomain: 'bluemind-61ea7.firebaseapp.com',
    storageBucket: 'bluemind-61ea7.firebasestorage.app',
    measurementId: 'G-MMF0ZWZD3X',
  );

}