name: blue_mind_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: 1.3.0
  flutter_staggered_grid_view: ^0.7.0
  google_sign_in: ^5.4.2
  cached_network_image: ^3.2.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  get: ^4.7.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  carousel_slider: ^5.0.0
  url_launcher: ^6.1.10
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/logoW.png
     - assets/logoW-invert.png
     - assets/species1.json
     - assets/flags/co.png
     - assets/flags/ar.png
     - assets/flags/cl.png
     - assets/flags/mx.png
     - assets/flags/pe.png
     - assets/album/Extinta(EX)/delfinBaijiMain.jpg
     - assets/album/Extinta(EX)/delfinBaiji1.jpg
     - assets/album/Extinta(EX)/delfinBaiji2.jpg
     - assets/album/Extinta(EX)/delfinBaiji3.jpg
     - assets/album/Extinta(EX)/pastinachusSephenMain.jpg
     - assets/album/Extinta(EX)/pastinachusSephen1.jpg
     - assets/album/Extinta(EX)/pastinachusSephen2.jpg
     - assets/album/Extinta(EX)/pastinachusSephen3.jpg
     - assets/album/Extinta(EX)/elliptioJayensisMain.jpg
     - assets/album/Extinta(EX)/elliptioJayensis1.jpg
     - assets/album/Extinta(EX)/elliptioJayensis2.jpg
     - assets/album/Extinta(EX)/elliptioJayensis3.jpg
     - assets/album/Extinta(EX)/chelonoidisAbingdoniiMain.jpg
     - assets/album/Extinta(EX)/chelonoidisAbingdonii1.jpg
     - assets/album/Extinta(EX)/chelonoidisAbingdonii2.jpg
     - assets/album/Extinta(EX)/chelonoidisAbingdonii3.jpg
     - assets/album/Extinta(EX)/stomolophusNecopsisMain.jpg
     - assets/album/Extinta(EX)/stomolophusNecopsis1.jpg
     - assets/album/Extinta(EX)/stomolophusNecopsis2.jpg
     - assets/album/Extinta(EX)/stomolophusNecopsis3.jpg
     - assets/album/Extinta(EX)/oculinaVaricosaMain.jpg
     - assets/album/Extinta(EX)/oculinaVaricosa1.jpg
     - assets/album/Extinta(EX)/oculinaVaricosa2.jpg
     - assets/album/Extinta(EX)/oculinaVaricosa3.jpg
     - assets/album/Extinta en estado silvestre (EW)/partulaFabaMain.jpg
     - assets/album/Extinta en estado silvestre (EW)/partulaFaba1.jpg
     - assets/album/Extinta en estado silvestre (EW)/partulaFaba2.jpg
     - assets/album/Extinta en estado silvestre (EW)/coralAcroporaSuharsonoiMain.jpg
     - assets/album/Extinta en estado silvestre (EW)/coralAcroporaSuharsonoi1.jpg
     - assets/album/Extinta en estado silvestre (EW)/coralAcroporaSuharsonoi2.jpg
     - assets/album/Extinta en estado silvestre (EW)/coralAcroporaSuharsonoi3.jpg
     - assets/album/En peligro crítico (CR)/vaquitaMarinaMain.jpg
     - assets/album/En peligro crítico (CR)/vaquitaMarina1.jpg
     - assets/album/En peligro crítico (CR)/vaquitaMarina2.jpg
     - assets/album/En peligro crítico (CR)/focaMonjeMediterráneoMain.jpg
     - assets/album/En peligro crítico (CR)/focaMonjeMediterráneo1.jpg
     - assets/album/En peligro crítico (CR)/focaMonjeMediterráneo2.jpg
     - assets/album/En peligro crítico (CR)/focaMonjeMediterráneo3.jpg
     - assets/album/En peligro crítico (CR)/lipotesVexilliferMain.jpg
     - assets/album/En peligro crítico (CR)/lipotesVexillifer1.jpg
     - assets/album/En peligro crítico (CR)/lipotesVexillifer2.jpg
     - assets/album/En peligro crítico (CR)/tortugaCareyMain.jpg
     - assets/album/En peligro crítico (CR)/tortugaCarey1.jpg
     - assets/album/En peligro crítico (CR)/tortugaCarey2.jpg
     - assets/album/En peligro crítico (CR)/tortugaCarey3.jpg
     - assets/album/En peligro crítico (CR)/atúnRojoAtlánticoMain.jpg
     - assets/album/En peligro crítico (CR)/atúnRojoAtlántico1.jpg
     - assets/album/En peligro crítico (CR)/coralCuernoAlceMain.jpg
     - assets/album/En peligro crítico (CR)/coralCuernoAlce1.jpg
     - assets/album/En peligro crítico (CR)/coralCuernoAlce2.jpg
     - assets/album/En peligro crítico (CR)/coralCuernoAlce3.jpg
     - assets/album/En peligro crítico (CR)/caballitoMarKnysnaMain.jpg
     - assets/album/En peligro crítico (CR)/caballitoMarKnysna1.jpg
     - assets/album/En peligro crítico (CR)/caballitoMarKnysna2.jpg
     - assets/album/En peligro crítico (CR)/pezSierraDientesGrandesMain.jpg
     - assets/album/En peligro crítico (CR)/pezSierraDientesGrandes1.jpg
     - assets/album/En peligro crítico (CR)/pezSierraDientesGrandes2.jpg
     - assets/album/En peligro crítico (CR)/pezSierraDientesGrandes3.jpg
     - assets/album/En peligro crítico (CR)/esturiónAdriáticoMain.jpg
     - assets/album/En peligro crítico (CR)/esturiónAdriático1.jpg
     - assets/album/En peligro crítico (CR)/esturiónAdriático2.jpg
     - assets/album/En peligro crítico (CR)/coralPilarMain.jpg
     - assets/album/En peligro crítico (CR)/coralPilar1.jpg
     - assets/album/En peligro crítico (CR)/coralPilar2.jpg
     - assets/album/En peligro crítico (CR)/coralPilar3.jpg
     - assets/album/En peligro crítico (CR)/tridacnaGigasMain.jpg
     - assets/album/En peligro crítico (CR)/tridacnaGigas1.jpg
     - assets/album/En peligro crítico (CR)/tridacnaGigas2.jpg
     - assets/album/En peligro crítico (CR)/tridacnaGigas3.jpg
     - assets/album/En peligro crítico (CR)/panulirusVersicolorMain.jpg
     - assets/album/En peligro crítico (CR)/panulirusVersicolor1.jpg
     - assets/album/En peligro crítico (CR)/panulirusVersicolor2.jpg
     - assets/album/En peligro crítico (CR)/panulirusVersicolor3.jpg
     - assets/album/En peligro (EN)/eubalaenaGlacialisMain.jpg
     - assets/album/En peligro (EN)/eubalaenaGlacialis1.jpg
     - assets/album/En peligro (EN)/eubalaenaGlacialis2.jpg
     - assets/album/En peligro (EN)/orcinusOrcaMain.jpg
     - assets/album/En peligro (EN)/orcinusOrca1.jpg
     - assets/album/En peligro (EN)/orcinusOrca2.jpg
     - assets/album/En peligro (EN)/orcinusOrca3.jpg
     - assets/album/En peligro (EN)/tiburonMartilloMain.jpg
     - assets/album/En peligro (EN)/tiburonMartillo1.jpg
     - assets/album/En peligro (EN)/tiburonMartillo2.jpg
     - assets/album/En peligro (EN)/tiburonMartillo3.jpg
     - assets/album/En peligro (EN)/pingüinoGalápagosMain.jpg
     - assets/album/En peligro (EN)/pingüinoGalápagos1.jpg
     - assets/album/En peligro (EN)/pingüinoGalápagos2.jpg
     - assets/album/En peligro (EN)/pingüinoGalápagos3.jpg
     - assets/album/En peligro (EN)/montastraeaFaveolataMain.jpg
     - assets/album/En peligro (EN)/montastraeaFaveolata1.jpg
     - assets/album/En peligro (EN)/montastraeaFaveolata2.jpg
     - assets/album/En peligro (EN)/montastraeaFaveolata3.jpg
     - assets/album/En peligro (EN)/dugongoMain.jpg
     - assets/album/En peligro (EN)/dugongo1.jpg
     - assets/album/En peligro (EN)/dugongo2.jpg
     - assets/album/En peligro (EN)/dugongo3.jpg
     - assets/album/En peligro (EN)/langostaFloridaMain.jpg
     - assets/album/En peligro (EN)/langostaFlorida1.jpg
     - assets/album/En peligro (EN)/langostaFlorida2.jpg
     - assets/album/En peligro (EN)/langostaFlorida3.jpg
     - assets/album/En peligro (EN)/calamarVampiroMain.jpg
     - assets/album/En peligro (EN)/calamarVampiro1.jpg
     - assets/album/En peligro (EN)/calamarVampiro2.jpg
     - assets/album/En peligro (EN)/calamarVampiro3.jpg
     - assets/album/En peligro (EN)/tortugaOliváceaMain.jpg
     - assets/album/En peligro (EN)/tortugaOlivácea1.jpg
     - assets/album/En peligro (EN)/tortugaOlivácea2.jpg
     - assets/album/En peligro (EN)/tortugaOlivácea3.jpg
     - assets/album/En peligro (EN)/pingüinoPenachoAmarilloMain.jpg
     - assets/album/En peligro (EN)/pingüinoPenachoAmarillo1.jpg
     - assets/album/En peligro (EN)/pingüinoPenachoAmarillo2.jpg
     - assets/album/En peligro (EN)/pingüinoPenachoAmarillo3.jpg
     - assets/album/En peligro (EN)/caballitoMarNarizCortaMain.jpg
     - assets/album/En peligro (EN)/caballitoMarNarizCorta1.jpg
     - assets/album/En peligro (EN)/caballitoMarNarizCorta2.jpg
     - assets/album/En peligro (EN)/caballitoMarNarizCorta3.jpg
     - assets/album/En peligro (EN)/mejillónAguaDulceChinaMain.jpg
     - assets/album/En peligro (EN)/mejillónAguaDulceChina1.jpg
     - assets/album/En peligro (EN)/medusaCajaAustralianaMain.jpg
     - assets/album/En peligro (EN)/medusaCajaAustraliana1.jpg
     - assets/album/En peligro (EN)/medusaCajaAustraliana2.jpg
     - assets/blog/1.jpg
     - assets/blog/2.jpg
     - assets/blog/3.jpg
     - assets/blog/4.jpg
     - assets/blog/5.jpg
     - assets/blog/6.jpg
     - assets/blog/7.jpg
     - assets/blog/8.jpg
     - assets/blog/9.jpg
     - assets/blog/10.jpg
     - assets/blog/11.jpg
     - assets/blog/12.jpg
     - assets/blog/13.jpg
     - assets/blog/14.jpg
     - assets/blog/15.jpg
     - assets/blog/16.jpg
     - assets/blog/17.jpg
     - assets/blog/18.jpg
     - assets/blog/19.jpg
     - assets/blog/20.jpg
     - assets/blog/21.jpg
     - assets/blog/22.jpg
     - assets/blog/23.jpg
     - assets/blog/24.jpg
     - assets/blog/25.jpg
     - assets/blog/26.jpg
     - assets/blog/27.jpg
     - assets/blog/28.jpg
     - assets/blog/29.jpg
     - assets/blog/30.jpg
     - assets/blog/31.jpg
     - assets/blog/32.jpg
     - assets/blog/33.jpg
     
    
     




     #- assets/libreria.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
